project:
  type: website
  output-dir: docs
website:
  title: "SNAP Vs Diet Quality"
  navbar:
    left:
      - href: Survey_Questions.qmd
        text: Survey Questions
      - href: Data_Collection.qmd
        text: Data Collection        
      - href: Data_Management.qmd
        text: Data Management
      - text: "Data Analysis"
        menu:
          - href: Imputations.qmd
            text: Imputations
          - href: Variable_Selection.qmd
            text: Variable Selection
          - href: Model_Diagnostics.qmd
            text: Model Diagnostics 
          - href: Campus_Type_Analysis.qmd
            text: Campus Type Analysis              
      - href: Manuscript_Files.qmd
        text: Manuscript Files
      - href: Statewide_and_Pilot2_Comparison.qmd
        text: 'Cohort Comparison'         
       

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

