---
title: "Summary"
---

> This site serves as a reference to all code and supplementary material used for the manuscript titled "A Cross-Sectional Study on the Associations Between SNAP Participation and Diet Quality Among California College Students." 

> College students in the United States have low quality diets consisting of frequent fast food intake, high sugar sweetened beverage (SSB) intake, and low fruit and vegetable (F&V) intake. Having a low income is one of the most prominent predictors of a low-quality diet, causing difficulties for low-income students to maintain a healthy diet in addition to the many other barriers to healthy eating that students face. Many low-income students are likely eligible to participate in the Supplemental Nutrition Assistance Program (SNAP), however, only an estimated 18% of likely eligible students in California are participating. This study analyzes the associations between SNAP use and fast food, SSB, and F&V intake among California college students.

> Self-reported data was collected using a cross-sectional study design. Three ordinal regression models were built with the dietary intake indicators as the dependent variables, SNAP status as the independent variable, and relevant covariates. SNAP status was divided into three groups: those that were currently using SNAP, those that were likely eligible non-recipients (LENRs), and those that were income-ineligible non-recipients (IINRs).

> After controlling for covariates, LENRs were more likely to consume fast food (OR: 1.67, 95% CI: 1.35 - 2.07, p < 0.001), and SSBs (OR: 1.34, 95% CI: 1.09 – 1.65, p = 0.006) and were less likely to consume F&Vs (OR: 0.55, 95% CI: 0.44 – 0.68, p < 0.001) compared to SNAP recipients. IINRs were also more likely to consume fast food (OR: 2.05, 95% CI: 1.44 - 2.92, p < 0.001), and SSBs (OR: 1.44, 95% CI: 1.06 – 1.95, p = 0.020) and were less likely to consume F&Vs (OR: 0.66, 95% CI: 0.45 – 0.97, p = 0.033) compared to SNAP recipients. 

> Although there were positive dietary associations with receiving SNAP benefits, an alarming number of students were still not eating enough F&Vs in all three groups, and more than half of the students consumed at least one serving of SSBs daily and one to two meals of fast food a week. Future research should investigate the efficacy of nutrition education, nutrition incentive programs, and SNAP participation in coordination with one another for improving college students' diets.

