---
title: "Statewide vs Pilot 2 Cohort Comparison"
format:
  html:
    code-fold: true
    code-summary: "Show the code"
---


```{r, include=FALSE}
knitr::opts_chunk$set(error = FALSE,warning = FALSE,message = FALSE,echo = TRUE)

library(gtsummary)
library(performance)
library(mice)
library(kableExtra)
library(dotwhisker)
library(ggplot2)
library(dplyr)
library(gridExtra)
library(grid)
library(tidymodels)


bns_imputed_mids <- readRDS(here::here("clean_data/imp_bns_combined_clean_mids.RData"))

bns_combined_imputed_df <- complete(bns_imputed_mids, fill = 3)

load("clean_data/bns_combined.Rdata")

chc.palette <- c("#B1D238", "#5782B0", "#FF914D") 
```




> Values are based on Non exponentiated Betas


```{r}
bns_imputed_mids_sw <- bns_imputed_mids %>% filter(Cohort == "Statewide")


bns_imputed_mids_sw2 <- bns_imputed_mids %>% filter(Cohort == "Statewide" &
                                                   school2 == "CSU" &
                                                   academic_level == "Junior" | academic_level == "Senior")


bns_imputed_mids_p2 <- bns_imputed_mids %>% filter(Cohort == "Pilot 2")


```


## Fast Food Ordinal



```{r}

ff.ordinal.mod <- with(bns_imputed_mids, MASS::polr(ff_cat~SNAP3 + Cohort + gender + race_eth + age + physical_activity + storage_room + health_conscious + living_with_family + cooking_confident + food_insecure_2item + paid_work_hours_tens + homelessness_year, Hess=TRUE))

ff.ordinal.mod.p2 <- with(bns_imputed_mids_p2, MASS::polr(ff_cat~SNAP3 + gender + race_eth + age + physical_activity + storage_room + health_conscious + living_with_family + cooking_confident + food_insecure_2item + paid_work_hours_tens + homelessness_year, Hess=TRUE))

ff.ordinal.mod.sw <- with(bns_imputed_mids_sw, MASS::polr(ff_cat~SNAP3 + gender + race_eth + age + physical_activity + storage_room + health_conscious + living_with_family + cooking_confident + food_insecure_2item + paid_work_hours_tens + homelessness_year, Hess=TRUE))

ff.ordinal.mod.sw2 <- with(bns_imputed_mids_sw2, MASS::polr(ff_cat~SNAP3 + gender + race_eth + age + physical_activity + storage_room + health_conscious + living_with_family + cooking_confident + food_insecure_2item + paid_work_hours_tens + homelessness_year, Hess=TRUE))


```



```{r, fig.height=7}

ff.ordinal.mod.tidy <- pool(ff.ordinal.mod) |> summary() %>%
  mutate(model = "Combined Model")
  

ff.ordinal.mod.p2.tidy <- pool(ff.ordinal.mod.p2) |> summary() %>%
  mutate(model = "Pilot 2 Only") %>% select(-df)

ff.ordinal.mod.sw.tidy <- pool(ff.ordinal.mod.sw) |> summary() %>%
  mutate(model = "Statewide Only") %>% select(-df)

ff.ordinal.mod.sw2.tidy <- pool(ff.ordinal.mod.sw2) |> summary() %>%
  mutate(model = "Statewide CSU/Juniors and Seniors") %>% select(-df)


ff_models <- bind_rows(ff.ordinal.mod.p2.tidy, ff.ordinal.mod.sw.tidy, ff.ordinal.mod.sw2.tidy, ff.ordinal.mod.tidy)


# Drop slopes from plot
ff_models <- ff_models[-c(17:19, 36:38, 55:57, 75:77), ]

dwplot(ff_models) + geom_vline(xintercept = 0,
               colour = "black",
               linetype = 1) + xlab("Beta and SE") + 
  theme(legend.position='top')  + guides(colour = guide_legend(nrow = 2, title = ""))






```







## SSB Ordinal

```{r}

ssb.ordinal.mod <- with(bns_imputed_mids, MASS::polr(ssb_cat~SNAP3 + Cohort + race_eth + gender + age + units_four + unpaid_work_hours_tens + paid_work_hours_tens + caregiving_hours_tens + health_conscious + storage_access + physical_activity + homelessness_year, Hess=TRUE))

ssb.ordinal.mod.p2 <- with(bns_imputed_mids_p2, MASS::polr(ssb_cat~SNAP3 + race_eth + gender + age + units_four + unpaid_work_hours_tens + paid_work_hours_tens + caregiving_hours_tens + health_conscious + storage_access + physical_activity + homelessness_year, Hess=TRUE))

ssb.ordinal.mod.sw <- with(bns_imputed_mids_sw, MASS::polr(ssb_cat~SNAP3 + race_eth + gender + age + units_four + unpaid_work_hours_tens + paid_work_hours_tens + caregiving_hours_tens + health_conscious + storage_access + physical_activity + homelessness_year, Hess=TRUE))


ssb.ordinal.mod.sw2 <- with(bns_imputed_mids_sw2, MASS::polr(ssb_cat~SNAP3 + race_eth + gender + age + units_four + unpaid_work_hours_tens + paid_work_hours_tens + caregiving_hours_tens + health_conscious + storage_access + physical_activity + homelessness_year, Hess=TRUE))




```


```{r, fig.height=7}


ssb.ordinal.mod.tidy <- pool(ssb.ordinal.mod) |> summary() %>%
  mutate(model = "Combined Model")

ssb.ordinal.mod.p2.tidy <- pool(ssb.ordinal.mod.p2) |> summary() %>%
  mutate(model = "Pilot 2 Only") %>% select(-df)

ssb.ordinal.mod.sw.tidy <- pool(ssb.ordinal.mod.sw) |> summary() %>%
  mutate(model = "Statewide Only") %>% select(-df)

ssb.ordinal.mod.sw2.tidy <- pool(ssb.ordinal.mod.sw2) |> summary() %>%
  mutate(model = "Statewide CSU/Juniors and Seniors") %>% select(-df)


ssb_models <- bind_rows(ssb.ordinal.mod.p2.tidy, ssb.ordinal.mod.sw.tidy, ssb.ordinal.mod.sw2.tidy,ssb.ordinal.mod.tidy)

# Drop slopes from plot
ssb_models <- ssb_models[-c(17:19, 36:38, 55:57, 75:77), ]

dwplot(ssb_models) + geom_vline(xintercept = 0,
               colour = "black",
               linetype = 1) + xlab("Beta and SE") + 
  theme(legend.position='top') + guides(colour = guide_legend(nrow = 2, title = ""))


```






## F&V Ordinal

```{r}

FV.ordinal.mod <- with(bns_imputed_mids, MASS::polr(fruits3~SNAP3 + Cohort + gender + race_eth + age  + health_conscious + cooking_confident + physical_activity + storage_room + food_insecure_2item + firstgen, Hess=TRUE))

FV.ordinal.mod.p2 <- with(bns_imputed_mids_p2, MASS::polr(fruits3~SNAP3 + gender + race_eth + age  + health_conscious + cooking_confident + physical_activity + storage_room + food_insecure_2item + firstgen, Hess=TRUE))

FV.ordinal.mod.sw <- with(bns_imputed_mids_sw, MASS::polr(fruits3~SNAP3 + gender + race_eth + age  + health_conscious + cooking_confident + physical_activity + storage_room + food_insecure_2item + firstgen, Hess=TRUE))

FV.ordinal.mod.sw2 <- with(bns_imputed_mids_sw2, MASS::polr(fruits3~SNAP3 + gender + race_eth + age  + health_conscious + cooking_confident + physical_activity + storage_room + food_insecure_2item + firstgen, Hess=TRUE))




```




```{r, fig.height=7}

FV.ordinal.mod.tidy <- pool(FV.ordinal.mod) |> summary() %>%
  mutate(model = "Combined Model")

FV.ordinal.mod.p2.tidy <- pool(FV.ordinal.mod.p2) |> summary() %>%
  mutate(model = "Pilot 2 Only") %>% select(-df)

FV.ordinal.mod.sw.tidy <- pool(FV.ordinal.mod.sw) |> summary() %>%
  mutate(model = "Statewide Only") %>% select(-df)

FV.ordinal.mod.sw2.tidy <- pool(FV.ordinal.mod.sw2) |> summary() %>%
  mutate(model = "Statewide CSU/Juniors and Seniors") %>% select(-df)


FV_models <- bind_rows(FV.ordinal.mod.p2.tidy, FV.ordinal.mod.sw.tidy, FV.ordinal.mod.sw2.tidy, FV.ordinal.mod.tidy)


# Drop slopes from plot
FV_models <- FV_models[-c(15:16, 31:32, 47:48, 64:65), ]


dwplot(FV_models) + geom_vline(xintercept = 0,
               colour = "black",
               linetype = 1) + xlab("Beta and SE")  + 
  theme(legend.position='top') + guides(colour = guide_legend(nrow = 2, title = ""))




```













